CPP = g++
MAIN = main.cpp
TARGET = test

CFLAGS = -Wall  -W -Wpedantic -std=c++11
LINKING = -lpthread -lgtest

default:  
	$(CPP) $(CFLAGS) main.cpp -o $(TARGET) $(LINKING)

clean:
	rm $(TARGET) *~ *.cpt

